trigger: none
# - main

pool:
  vmImage: ubuntu-latest

variables:
  acr_name: acr4aks13579
  tag: 1.0.0-$(Build.BuildId)

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'Azure subscription 1(b19338e5-368e-4f1d-b894-d5bdfe7a3cf1)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t $(acr_name).azurecr.io/webapp:$(tag) app-dotnet
      az acr login -n $(acr_name)
      docker push $(acr_name).azurecr.io/webapp:$(tag)
      
- task: replacetokens@3
  inputs:
    rootDirectory: '02_kubernetes_aks'
    targetFiles: 'app-deploy.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    tokenPrefix: '__'
    tokenSuffix: '__'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- script: cat 02_kubernetes_aks/app-deploy.yaml
  displayName: View app-deploy.yaml

- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(b19338e5-368e-4f1d-b894-d5bdfe7a3cf1)'
    azureResourceGroup: 'dakar-dev-1280-RG'
    kubernetesCluster: 'aks-cluster-dev'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
